[site]
title = "Yicheng Zheng"
description = "PhD candidate at Florida State University."
favicon = "/favicon.png"
last_updated = "Jan 9, 2026"

[author]
name = "Yicheng Zheng"
chinese_name = "征亦诚"
title = "PhD Candidate"
institution = "Florida State University"
avatar = "/bio.png"

[social]
# Contact information (leave blank or delete to hide)

email = "yzheng@neuro.fsu.edu"
location = "Tallahassee, FL"
location_url = "https://maps.app.goo.gl/7GzeV3L1CLvN7rHA9"
location_details = [
  "1107 W Call St, Tallahassee, FL"
]
google_scholar = "https://scholar.google.com/citations?user=rt9RMvEAAAAJ&hl=en"
orcid = "https://orcid.org/my-orcid?orcid=0009-0003-6403-7750"
github = "https://github.com/zheng1ch"
linkedin = "https://www.linkedin.com/in/zhengych/"
# x = "https://x.com/zheng1ch"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Posters"
type = "page"
target = "posters"
href = "/posters"

# [[navigation]]
# title = "Awards"
# type = "page"
# target = "awards"
# href = "/awards"

# [[navigation]]
# title = "Services"
# type = "page"
# target = "services"
# href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"

[[navigation]]
title = "Playground"
type = "page"
target = "playground"
href = "/playground"

[[navigation]]
title = "Travel"
type = "page"
target = "flights"
href = "/flights"
hidden = true

[[navigation]]
title = "Visitors Map"
type = "page"
target = "MapVisitors"
href = "/MapVisitors"
hidden = true

[[navigation]]
title = "Mood tracking 2025"
type = "page"
target = "mood_tracking_2025"
href = "/mood_tracking_2025"
hidden = true

